version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
  settings:
    govet:
      enable:
        # flag unkeyed fields in composite literals of imported struct types
        - composites
